import '@/assets/styles/global.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import AppWrap from '@/components/app-wrap/app-wrap';
import { dir } from 'i18next';
import { Languages } from '@/config';
import { PageProps } from '@/interfaces';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return Languages.map((lng) => ({ lng }));
}

export default function RootLayout({ children, params: { lng } }: PageProps & { children: React.ReactNode }) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className} suppressHydrationWarning>
        <AppWrap>{children}</AppWrap>
      </body>
    </html>
  );
}
