/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CpDebug {
    }
    interface CpExample {
    }
}
declare global {
    interface HTMLCpDebugElement extends Components.CpDebug, HTMLStencilElement {
    }
    var HTMLCpDebugElement: {
        prototype: HTMLCpDebugElement;
        new (): HTMLCpDebugElement;
    };
    interface HTMLCpExampleElement extends Components.CpExample, HTMLStencilElement {
    }
    var HTMLCpExampleElement: {
        prototype: HTMLCpExampleElement;
        new (): HTMLCpExampleElement;
    };
    interface HTMLElementTagNameMap {
        "cp-debug": HTMLCpDebugElement;
        "cp-example": HTMLCpExampleElement;
    }
}
declare namespace LocalJSX {
    interface CpDebug {
    }
    interface CpExample {
    }
    interface IntrinsicElements {
        "cp-debug": CpDebug;
        "cp-example": CpExample;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cp-debug": LocalJSX.CpDebug & JSXBase.HTMLAttributes<HTMLCpDebugElement>;
            "cp-example": LocalJSX.CpExample & JSXBase.HTMLAttributes<HTMLCpExampleElement>;
        }
    }
}
